Repository BigData23th/MachineLearning, pull requests merged in 2023-03, with the labels that each got.

#17 2023.03.20.(월) 회고_JuHS
  JuHS/README.md
  JuHS/ch08_ML_01_선형회귀(JuHS).ipynb
  JuHS/ch08_ML_02_로지스틱회귀(JuHS).ipynb
  JuHS/first_model.pkl
  README.md
Labels: TIL, 4줄일기

#23 0320 회고
  Myun9hyun/ch08_ML_01_선형회귀.ipynb
  Myun9hyun/ch08_ML_02_로지스틱회귀_Myun9hyun.ipynb
Labels: TIL, 4줄일기

#21 2023.03.20 회고
  hiid0726/ch07_ML_01_선형회귀_ym.ipynb
  hiid0726/ch08_ML_02_로지스틱회귀_ym.ipynb
  hiid0726/readme.md
Labels: TIL, 4줄일기

#24 03/20
  ch07_ML_01_선형회귀.ipynb
  ch08_ML_02_로지스틱회귀.ipynb
Labels: TIL, KPT

#29 3월 17일 14일차 회고
  Yeaaaaaaah /ch08_ML_01_선형회귀.ipynb
  Yeaaaaaaah /ch08_ML_02_로지스틱회귀.ipynb
  Yeaaaaaaah /ch08_ML_03_KNN.ipynb
Labels: TIL, STAR

#30 23.03.20 수업 회고
  JaejinLee1215/ch08_ML_01_선형회귀_이재진.ipynb
  JaejinLee1215/ch08_ML_02_로지스틱회귀_이재진.ipynb
  JaejinLee1215/ch08_ML_03_KNN_이재진.ipynb
  JaejinLee1215/first_model.pkl
  JaejinLee1215/submission.csv
  ch08_01+02_복습.ipynb
Labels: TIL, STAR

#31 23.03.20 회고
  공부자료/ch08_ML_01_선형회귀_ChoiSG.ipynb
  공부자료/ch08_ML_02_로지스틱회귀_ChoiSg(필기완).ipynb
  공부자료/ch08_ML_03_KNN_ChoiSG.ipynb
  공부자료/ch08_ML_04_NaiveBayes_ChoiSG.ipynb
  복습/ch08_ML_복습_01+02.ipynb
Labels: TIL, 4줄일기

#32 2023_03_20_회고
  cc5547/2023_03_20_ch07_ML_01_선형회귀.ipynb
  cc5547/2023_03_20_ch08_ML_02_로지스틱회귀.ipynb
Labels: TIL, 4줄일기

#33 15일차 회고
  jaiwon880/ch07_ML_01_선형회귀.ipynb
  jaiwon880/ch08_ML_02_로지스틱회귀.ipynb
  jaiwon880/ch08_ML_03_KNN.ipynb
Labels: TIL, KPT

#36 2023/03/21수업
  JoySoon/ch08_ML_03_KNN_KSW.ipynb
  JoySoon/ch08_ML_04_NaiveBayes_KSW.ipynb
Labels: TIL, 4줄일기

#37 회고
  jinu/CH08_03+04.ipynb
  jinu/ch07_ML_01_선형회귀_qus0in.ipynb
  jinu/ch08_ML_03_KNN_qus0in.ipynb
  jinu/ch08_ML_04_NaiveBayes_qus0in.ipynb
Labels: TIL, 4줄일기

#38 230321 회고
  tkd8973/Knn+NaiveBayes+Confusion_Matrix.ipynb
  tkd8973/Naive_Bayes.ipynb
Labels: TIL, KPT

#39 03/21
  whataLIN/ch08_ML_01_선형회귀.ipynb
  whataLIN/ch08_ML_02_로지스틱회귀.ipynb
  whataLIN/ch08_ML_03_KNN.ipynb
  whataLIN/ch08_ML_04_NaiveBayes.ipynb
Labels: TIL, KPT

#40 3월 21일 16일차 회고
  Yeaaaaaaah /ch08_ML_04_NaiveBayes.ipynb
Labels: TIL, 4줄일기

#41 20123.03.21 회고
  hiid0726/ch08_ML_03_KNN_ym.ipynb
  hiid0726/ch08_ML_04_NaiveBayes_ym.ipynb
Labels: TIL, 4줄일기

#43 03-21 회고
  Myun9hyun/ch08_ML_03_KNN_Myun9hyun.ipynb
  Myun9hyun/ch08_ML_04_NaiveBayes.ipynb
Labels: TIL, STAR

#45 23.03.21 수업 회고
  JaejinLee1215/ch08_03+04_복습.ipynb
  JaejinLee1215/ch08_ML_04_NaiveBayes_이재진.ipynb
Labels: TIL, STAR

#47 16일차 회고
  jaiwon880/CH08_03+04.ipynb
  jaiwon880/ch08_ML_04_NaiveBayes.ipynb
  jaiwon880/ch08_ML_05_DecisionTree.ipynb
  jaiwon880/ch08_ML_06_RandomForest_중고차_가격_예측.ipynb
Labels: TIL, KPT

#49 2023/03/22 수업
  JoySoon/ch08_ML_05_DecisionTree_KSW.ipynb
  JoySoon/ch08_ML_06_RandomForest_KSW.ipynb
Labels: TIL, 4줄일기

#50 03/22
  whataLIN/ch08_ML_05_DecisionTree.ipynb
  whataLIN/ch08_ML_06_RandomForest.ipynb
  whataLIN/ch08_ML_07_XGBoost.ipynb
Labels: TIL, KPT

#51 2023.03.22
  zihvvan/CH08_01+02_복습.ipynb
  zihvvan/CH08_03+04_복습.ipynb
  zihvvan/CH08_05+06_복습.ipynb
  zihvvan/ch08_ML_03_KNN.ipynb
  zihvvan/ch08_ML_04_NaiveBayes.ipynb
  zihvvan/ch08_ML_05_DecisionTree.ipynb
  zihvvan/ch08_ML_06_RandomForest.ipynb
  zihvvan/ch08_ML_07_XGBoost.ipynb
Labels: TIL, 4줄일기

#52 23.03.22 수업 회고
  JaejinLee1215/ch08_05+06_복습.ipynb
  JaejinLee1215/ch08_ML_05_DecisionTree_이재진.ipynb
  JaejinLee1215/ch08_ML_06_RandomForest_이재진.ipynb
Labels: TIL, STAR

#53 03-22 회고
  Myun9hyun/ch08_ML_05_DecisionTree.ipynb
  Myun9hyun/ch08_ML_06_RandomForest.ipynb
  Myun9hyun/ch08_ML_07_XGBoost.ipynb
Labels: TIL, KPT

#54 3월 22일 17일차
  Yeaaaaaaah /ch08_ML_05_DecisionTree.ipynb
  Yeaaaaaaah /ch08_ML_06_RandomForest.ipynb
  Yeaaaaaaah /ch08_ML_07_XGBoost.ipynb
Labels: TIL, 4줄일기

#55 23. 03. 22 회고
  CHOISEONGGU/공부자료/ch08_ML_01_선형회귀_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch08_ML_02_로지스틱회귀_ChoiSg(필기완).ipynb
  CHOISEONGGU/공부자료/ch08_ML_03_KNN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch08_ML_04_NaiveBayes_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch08_ML_05_DecisionTree_ChoiSg.ipynb
  CHOISEONGGU/공부자료/ch08_ML_06_RandomForest_ChoiSG.ipynb
  CHOISEONGGU/복습/CH08_03+04_복습.ipynb
  CHOISEONGGU/복습/ch08_05+06_복습.ipynb
  CHOISEONGGU/복습/ch08_ML_복습_01+02.ipynb
Labels: TIL, 4줄일기

#62 17일차 회고
  jaiwon880/CH08_05+06복습.ipynb
  jaiwon880/ch08_ML_07_XGBoost_커플성사여부예측.ipynb
  jaiwon880/ch08_ML_08_LightGBM_이상거래예측.ipynb
  jaiwon880/ch08_ML_09_KMeansClustering.ipynb
Labels: TIL, KPT

#61 03-23 회고
  Myun9hyun/ch08_ML_07_XGBoost.ipynb
  Myun9hyun/ch08_ML_08_LightGBM.ipynb
Labels: TIL, KPT

#60 2023.03.23 회고
  README.md
  hiid0726/ch08_ML_05_DecisionTree_ym.ipynb
  hiid0726/ch08_ML_06_RandomForest_ym.ipynb
  hiid0726/ch08_ML_07_XGBoost_ym.ipynb
Labels: TIL, 4줄일기

#57 2023/03/23 수업
  JoySoon/ch08_ML_07_XGBoost_KSW.ipynb
Labels: TIL, STAR

#58 0323 회고
  sunghuncho/CH08_05+06.ipynb
  sunghuncho/CH08_07+08.ipynb
  sunghuncho/ch07_ML_01_선형회귀_공유안.ipynb
  sunghuncho/ch08_ML_02_로지스틱회귀_sunghuncho.ipynb
  sunghuncho/ch08_ML_03_KNN_sunghuncho.ipynb
  sunghuncho/ch08_ML_04_NaiveBayes_sunghuncho.ipynb
  sunghuncho/ch08_ML_07_XGBoost_sunghuncho.ipynb
  sunghuncho/ch08_ML_09_KMeansClustering_sunghuncho.ipynb
Labels: TIL, 4줄일기

#59 23.03.23 회고
  CHOISEONGGU/공부자료/ch08_ML_07_XGBoost_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch08_ML_08_LightGBM_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch08_ML_09_KMeansClustering_ChoiSG.ipynb
  CHOISEONGGU/복습/ch08_07+08_복습.ipynb
Labels: TIL, 4줄일기

#64 2023.03.24 회고
  hiid0726/ch08_ML_09_KMeansClustering_ym.ipynb
  hiid0726/ch08_ML_10_PCA_ym.ipynb
Labels: TIL, 4줄일기

#65 230324 회고
  tkd8973/Boost+LGBM+FE+Confusion.ipynb
  tkd8973/Tree,FE,RF.ipynb
Labels: TIL, KPT

#66 2023.03.24
  zihvvan/CH08_07+08_복습.ipynb
  zihvvan/ch08_ML_08_LightGBM.ipynb
  zihvvan/ch08_ML_09_KMeansClustering.ipynb
  zihvvan/ch08_ML_10_PCA.ipynb
Labels: TIL, KPT

#67 3월 24일 19일차 회고
  Yeaaaaaaah /ch08_ML_08_LightGBM.ipynb
  Yeaaaaaaah /ch08_ML_09_KMeansClustering.ipynb
  Yeaaaaaaah /ch08_ML_10_PCA.ipynb
Labels: TIL, KPT

#77 19일차 회고
  jyeongvv/CH08_03+04_복습.ipynb
  jyeongvv/ch07_ML_01_선형회귀.ipynb
  jyeongvv/ch08_01+02_복습.ipynb
  jyeongvv/ch08_ML_03_KNN.ipynb
  jyeongvv/ch08_ML_04_NaiveBayes.ipynb
  jyeongvv/ch08_ML_05_DecisionTree(결정트리).ipynb
  jyeongvv/ch08_ML_06_RandomForest.ipynb
  jyeongvv/ch08_ML_07_XGBoost.ipynb
Labels: TIL, KPT

#68 2023/03/24 수업
  JoySoon/ch08_ML_08_LightGBM_KSW.ipynb
  JoySoon/ch08_ML_09_KMeansClustering_KSW.ipynb
  JoySoon/ch08_ML_10_PCA_KSW.ipynb
Labels: TIL, 4줄일기

#69 0324
  andy9806/0320_1(linear_regression).ipynb
  andy9806/0320_1.ipynb
  andy9806/0320_2(logisticregression).ipynb
  andy9806/0324.html
Labels: TIL, STAR

#70 23.03.24 회고
  CHOISEONGGU/공부자료/ch08_ML_10_PCA_ChoiSG.ipynb
Labels: TIL, 4줄일기

#71 회고
  jinu/CH08_05+06.ipynb
  jinu/ch08_ML_05_DecisionTree.ipynb
  jinu/ch08_ML_06_RandomForest.ipynb
  jinu/ch08_ML_07_XGBoost.ipynb
  jinu/ch08_ML_08_LightGBM.ipynb
  jinu/ch08_ML_09_KMeansClustering.ipynb
  jinu/ch08_ML_10_PCA.ipynb
Labels: TIL, 4줄일기

#72 0324 회고
  sunghuncho/ch08_ML_08_LightGBM_sunghuncho.ipynb
  sunghuncho/ch08_ML_10_PCA_sunghuncho.ipynb
Labels: TIL, 4줄일기

#73 18일차 회고
  jaiwon880/ch08_ML_10_PCA.ipynb
  web/아파트_실거래가_2월_데이터.ipynb
Labels: TIL, KPT

#74 03-24회고
  Myun9hyun/ch08_ML_09_KMeansClustering.ipynb
  Myun9hyun/ch08_ML_10_PCA.ipynb
Labels: TIL, STAR

#75 03-24 회고
  Kwak99/CH08_01+02_ipynb의_사본.ipynb
  Kwak99/CH08_03+04_ipynb의_사본.ipynb
  Kwak99/CH08_05+06_ipynb의_사본.ipynb
  Kwak99/CH08_07+08_ipynb의_사본.ipynb
  Kwak99/MachineProject/app.py
  Kwak99/MachineProject/hello
  Kwak99/MachineProject/project.csv
  Kwak99/ch08_ML_03_KNN_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_04_NaiveBayes_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_05_DecisionTree_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_07_XGBoost_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_08_LightGBM_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_09_KMeansClustering_wa99_ipynb의_사본.ipynb
  Kwak99/ch08_ML_10_PCA_wa99_ipynb의_사본.ipynb
  곽99/ch08_ML_06_RandomForest_wa99_ipynb의_사본.ipynb
Labels: TIL, 4줄일기

#76 2023.03.24 회고
  mastgm0817/ch08_ML_05_DecisionTree.ipynb
  mastgm0817/ch08_ML_06_RandomForest.ipynb
  mastgm0817/ch08_ML_07_XGBoost.ipynb
  mastgm0817/ch08_ML_08_LightGBM.ipynb
  mastgm0817/ch08_ML_09_KMeansClustering.ipynb
  mastgm0817/ch08_ML_10_PCA.ipynb
Labels: TIL, KPT

#87 03-29 회고
  Kwak99/CH08_08+09+10_ipynb의_사본.ipynb
  Kwak99/MachineProject/app.py
  Kwak99/MachineProject/hello
  Kwak99/MachineProject/project.csv
  MachineLearning/Kwak99/MLProject/MLNtest5_ipynb의_사본.ipynb
Labels: TIL, KPT
